apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcclient
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpcclient
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rpcclient
    spec:
      containers:
      - name: rpcclient
        image: docker.sharkgulf.cn/huhui/rpcclient:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - "exec tail -f /dev/null"
      imagePullSecrets:
      - name: sharkgulf
      restartPolicy: Always
