apiVersion: apps/v1
kind: Deployment
metadata:
  name: rpcserver
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rpcserver
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rpcserver
    spec:
      containers:
      - name: rpcserver
        image: docker.sharkgulf.cn/huhui/rpcserver:latest
        imagePullPolicy: Always
        command:
          - sh
          - -c
          - "exec tail -f /dev/null"
        ports:
        - name: rpcport
          containerPort: 8080
      imagePullSecrets:
      - name: sharkgulf
      restartPolicy: Always
